name: Generate Debug APK        

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    
jobs:
  upload_testable_apk:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Gradlew assembleDebug
      run: ./gradlew assembleDebug 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: sunflower-debug-$GITHUB_RUN_NUMBER
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Display the build number
      run: echo GITHUB_RUN_NUMBER
      shell: bash  
    - name: Display the path
      run: echo $PATH
      shell: bash
    - name: Display the id
      run: echo $GITHUB_RUN_ID
      shell: bash
    - name: Display the id 2
      run: echo GITHUB_RUN_ID
      shell: bash  
  
